OpenAI_API_Base: ""
API_key_list:
  -
chunk_size: 50
model_name_emb: "text-embedding-3-small"
seed_file_path: "../seed_data/"
all_file_path: "../all_data/"
ke_entity_extratction_prompt: "../prompt/kg_exploration/entity_extraction"
ke_relation_extratction_prompt: "../prompt/kg_exploration/relation_extraction"
ke_entity_labeling_prompt: "../prompt/kg_exploration/entity_type_label"
ke_entity_type_fusion_prompt: "../prompt/kg_exploration/entity_type_fusion"
ke_relation_type_fusion_prompt: "../prompt/kg_exploration/relation_type_fusion"
kc_entity_extratction_prompt: "../prompt/kg_construction/entity_extraction"
kc_relation_extratction_prompt: "../prompt/kg_construction/relation_extraction"
Suggestion_prompt: "../prompt/kg_exploration/ActionInsight"
save_ke_entity_path: "../output/kg_exploration/entity.csv"
save_suggestions_path: "../output/kg_exploration/suggestions.csv"
save_ke_relation_path: "../output/kg_exploration/our_llama.csv"
save_ke_entity_label_path: "../output/kg_exploration/entity_label.csv"
save_ke_entity_type_path: "../output/kg_exploration/entity_type.csv"
save_ke_relation_type_path: "../output/kg_exploration/relation_type.csv"
save_kc_entity_path: "../output/kg_construction/entity.csv"
save_kc_relation_path: "../output/kg_construction/our_llama.csv"
save_kr_schema_path: "../output/kg_refinement/schema.csv"
save_kg_schema_path: "../output/kg_exploration/kg_schema.csv"

